
spring:
  application:
    name: candidate-service

  datasource:
    url: jdbc:postgresql://localhost:5432/cvscan
    username: cvscan
    password: cvscan
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.migration-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: candidate-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.tunduk.candidateservice.dto.event"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: MANUAL

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  kafka:
    topics:
      cv-parsed: cv.parsed
      status-changed: candidate.status.changed


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId:-no-corr}] [%-5level] %logger{36} - %msg%n"
  level:
    root: INFO
    kg.tunduk.cvscan: DEBUG
    org.springframework.kafka: INFO