spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    kg.tunduk.cvscan: DEBUG
    org.springframework.kafka: WARN
    org.liquibase: INFO